"""系统级入口安装/卸载。

解决 `uv tool install` 安装的 confmirror 在 `sudo` 环境下因 PATH 问题找不到的问题。
"""

import os
import shutil
import sys
from pathlib import Path

SYSTEM_BIN_DIR = Path("/usr/local/bin")
WRAPPER_MARKER = (
    "# ConfMirror system wrapper — generated by `confmirror install-system`"
)


def _detect_source_path() -> Path:
    """检测当前 confmirror 可执行文件的完整路径。"""
    # 策略 1：sys.argv[0] 如果是绝对路径，直接用它
    # （sudo 执行时，shell 通常会把解析后的完整路径传进来）
    argv0 = sys.argv[0]
    if os.path.isabs(argv0):
        p = Path(argv0)
        if p.exists():
            return p.resolve()

    # 策略 2：在 PATH 中查找
    which_path = shutil.which("confmirror")
    if which_path:
        p = Path(which_path)
        if p.exists():
            return p.resolve()

    raise RuntimeError(
        "无法自动检测 confmirror 的路径。"
        "请显式指定：confmirror install-system --source-path /path/to/confmirror"
    )


def install_system_entry(source_path: Path | None = None) -> bool:
    """在 /usr/local/bin/ 创建 wrapper 脚本，使 `sudo confmirror` 可用。

    Args:
        source_path: confmirror 原始可执行文件的完整路径。
                     为 None 时自动检测。

    Returns:
        bool: 成功返回 True，失败返回 False
    """
    if os.name == "nt":
        raise RuntimeError("install-system 不支持 Windows")

    if os.getuid() != 0:
        raise PermissionError(
            "install-system 需要 root 权限写入 /usr/local/bin/。\n"
            "请执行：sudo confmirror install-system"
        )

    if source_path is None:
        source_path = _detect_source_path()
    else:
        source_path = Path(source_path).resolve()

    if not source_path.exists():
        raise FileNotFoundError(f"源路径不存在: {source_path}")

    target = SYSTEM_BIN_DIR / "confmirror"

    # 如果已存在同名文件，检查是否是我们之前创建的 wrapper
    if target.exists():
        content = target.read_text(encoding="utf-8")
        if WRAPPER_MARKER not in content:
            raise RuntimeError(
                f"{target} 已存在且不是 ConfMirror 创建的 wrapper，"
                "为避免覆盖其他程序，安装已中止。"
            )

    wrapper_content = (
        f"#!/bin/sh\n"
        f"{WRAPPER_MARKER}\n"
        f"# Source: {source_path}\n"
        f'exec "{source_path}" "$@"\n'
    )

    try:
        target.write_text(wrapper_content, encoding="utf-8")
        target.chmod(0o755)
    except OSError as e:
        raise RuntimeError(f"写入 {target} 失败: {e}")

    return True


def uninstall_system_entry() -> bool:
    """移除 /usr/local/bin/confmirror wrapper 脚本。

    Returns:
        bool: 成功返回 True，未找到或失败返回 False
    """
    if os.name == "nt":
        raise RuntimeError("uninstall-system 不支持 Windows")

    if os.getuid() != 0:
        raise PermissionError(
            "uninstall-system 需要 root 权限修改 /usr/local/bin/。\n"
            "请执行：sudo confmirror uninstall-system"
        )

    target = SYSTEM_BIN_DIR / "confmirror"

    if not target.exists():
        return False

    content = target.read_text(encoding="utf-8")
    if WRAPPER_MARKER not in content:
        raise RuntimeError(
            f"{target} 不是 ConfMirror 创建的 wrapper，"
            "为避免误删其他程序，卸载已中止。"
        )

    try:
        target.unlink()
    except OSError as e:
        raise RuntimeError(f"删除 {target} 失败: {e}")

    return True
